---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: ohioit
name: roles
version: 0.1.0
readme: README.md
authors:
  - Kyle Barstow <barstown@ohio.edu> (https://github.com/barstown)
description: This Ansible collection provides general purpose roles for system configuration.
license_file: LICENSE
tags:
  - linux
  - roles
  - sysops
  - windows
# dependencies: {}
repository: https://github.com/ohioit/ansible-collection-roles
# documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ohioit/ansible-collection-roles
issues: https://github.com/ohioit/ansible-collection-roles/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .devcontainer
  - .editorconfig
  - .github
  - .gitignore
  - .vale.ini
  - .vscode
  - changelogs/.plugin-cache.yaml
