---
name: New Release

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    name: Create release draft
    runs-on: ubuntu-latest
    if: github.repository == 'ohioit/ohioit.roles'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Calculate next version
        id: version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DRY_RUN: true

      - name: echo calculated version
        run: |
          echo "version: ${{ steps.version.outputs.new_tag }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install antsibull-changelog
        run: pipx install antsibull-changelog

      - name: Generate changelog
        run: |
          antsibull-changelog release --version ${{ steps.version.outputs.new_tag }}

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update changelog for ${{ steps.version.outputs.new_tag }}
          file_pattern: "CHANGELOG.* changelogs/changelog.yaml changelogs/fragments/*"
          commit_user_name: "OHIOIT CI"
          commit_user_email: "oit-sea@ohio.edu"

      # - name: Read release notes
      #   id: release_notes
      #   run: |
      #     echo "body<<EOF" >> $GITHUB_OUTPUT
      #     sed -n '/^## /,/^## /p' CHANGELOG.rst | head -n -1 >> $GITHUB_OUTPUT
      #     echo "EOF" >> $GITHUB_OUTPUT

      - name: Delete old drafts
        uses: hugo19941994/delete-draft-releases@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create release draft
        uses: softprops/action-gh-release@v2
        with:
          # body: ${{ steps.release_notes.outputs.body }}
          body_path: CHANGELOG.md
          draft: true
          name: ${{ steps.version.outputs.new_tag }}
          tag_name: ${{ steps.version.outputs.new_tag }}
