---
name: Release Publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    if: github.repository == 'ohioit/ohioit.roles'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ansible packages
        run: |
          pipx install ansible-core
          pipx install antsibull-changelog

      - name: Finalize changelog
        run: |
          antsibull-changelog release

      - name: Build collection
        run: ansible-galaxy collection build

      # - name: Publish to Ansible Galaxy
      #   run: ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.CSI_GALAXY_API_KEY }}
